### PR TITLE
Misc3

### PR DESCRIPTION
**Pull request by snoweye**
This one should be ok.

### CODE REVIEW

**Comment by wrathematics** [comment]
I don't understand what this does. It includes a lot of my previous commits...

**Comment by snoweye** [comment]
- You need to let Travis install the ``libsodium-dev`` and ``install.packages("sodium")``.
- Suggest to use ``.rr_env`` and ``.pbd_env``

**Comment by snoweye** [comment]
OMG.... click in wrong button....

**Comment by snoweye** [comment]
I don't know what happen...I am trying to pull from the latest one, otherwise I will screw up a lot of your changes. Then, I make a branch to add something may not be needed. So....

**Comment by snoweye** [comment]
5 commits are probably wrong, but 11 file changes are correct. May be the branch casts the commits.

**Comment by wrathematics** [comment]
Yeah, I don't understand what this is intended to do. It seems like a different version of `exit(FALSE)`, but I'm not sure. Might need to think about it more...

**Comment by snoweye** [comment]
- It only affect an interactive UI. I tried to bring it down as well if ``q.server=T`` and ``client.only=F``.
- I tried to have the interactive server print log instantaneously, but can not. This will be good for debugging. Then, I want the UI closes as well after exiting the ``while(TRUE)``.

**Comment by wrathematics** [comment]
I still don't understand what this does.

Right now, the client can only be used interactively.  I plan on adding a batch/source() version soon.

**Comment by snoweye** [comment]
It is only for the server when it is interactive, but no change to the client. If someone (me) uses ``R`` and ``source`` to initial server, then I want the UI does not only shut down, but also quits the terminal.

**Comment by wrathematics** [comment]
ohhh I see

Let me  come back to this in the morning, but I think I see (ps, if you can figure out why travis-ci is breaking, I'd love to know the reason...)

**Pull request merged**
